/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * prueba.java
 *
 * Created on 22/07/2011, 09:50:36
 */
package migracioncreditos;

import ConexionAccess.BaseAccess;
import ConexionFirebird.ConexionF;
import Entidades.Indice;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author analian
 */
public class Prueba extends javax.swing.JFrame {

    /** Creates new form prueba */
    public Prueba() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Prueba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButton1)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //  BaseAccess ba = new BaseAccess();
     /// String i= "0101010002";
       // ResultSet o = ba.proyectosParamCuotas(i);
        ConexionF be= new ConexionF();
       be.buscarCredito(BigDecimal.ZERO);
        // AObjetoiBonificacion objiBonificacion = new AObjetoiBonificacion();
      //  try {
      //      objiBonificacion.migrarAObjetoibonificacion();
            //ResultSet paramCuotas = be.proyectosAportes("0101010022");
         /*   try {
                while (paramCuotas.next()) {
                System.out.println(paramCuotas.getObject(1));
              /* try {
                    while (o.next()) {
                        System.out.println("el object funciona y  este su segunda columna" + o.getObject(2));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, null, ex);
                }
            // ResultSet o = ba.desembolsos();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, null, ex);
        }*/
       // } catch (SQLException ex) {
       //     Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, null, ex);
      //  }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
